### ISSUE TITLE
Unable to install dev-lang/fsharp

### ISSUE THREAD

**Issue by ArsenShnurkov** [gentoo/dotnet#196]
<pre>
		Unable to find version '2.6.4' of package 'NUnit.Runners'.
		Unable to find version '2.0.3' of package 'FsCheck'.
/var/tmp/portage/dev-lang/fsharp-4.0.0.4/work/fsharp-4.0.0.4/src/FSharpSource.targets: error : Command 'mono --runtime=v4.0.30319 /var/tmp/portage/dev-lang/fsharp-4.0.0.4/work/fsharp-4.0.0.4/src/fsharp/FSharp.Build-proto/../../../.nuget/NuGet.exe restore packages.config -PackagesDirectory packages' exited with code: 1.
</pre>

fsharp should be installed for rolling monodevelop tarball (i don't know why).

It's not good to use external binaries in source-based distribution. In this case untrusted nonsystem NuGet.exe is used.

**Comment by Heather** [comment]
same with last version? https://github.com/gentoo/dotnet/commit/0e9d634d3e156c6b379cc88f77a2c858b2b82419

**Comment by ArsenShnurkov** [comment]
<code>>>> dev-lang/fsharp-4.0.1.1 merged.</code>

but i still insist that it builds not in gentoo way, so I am not closing this bug

**Comment by Despair** [comment]
@ArsenShnurkov I'm not agreed with keeping this bug opened because of it's complexity, I doubt people will start working on monster task just because it's not gentoo way. Mind splitting it into sub-tasks for getting into direction and open issue for first task so it will look at least real for someone to take.
