### ISSUE TITLE
libgit2sharp build fails

### ISSUE THREAD

**Issue by piedar** [gentoo/dotnet#256]
```
# emerge -v dev-dotnet/libgit2sharp
```

...

```
Build FAILED.
Errors:

/var/tmp/portage/dev-dotnet/libgit2sharp-0.22/work/libgit2sharp-8daef23223e1374141bf496e4b310ded9ae4639e/LibGit2Sharp.sln (default targets) ->
(Build target) ->
/var/tmp/portage/dev-dotnet/libgit2sharp-0.22/work/libgit2sharp-8daef23223e1374141bf496e4b310ded9ae4639e/LibGit2Sharp/LibGit2Sharp.csproj (default targets) ->
/usr/lib64/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

    CSC: error CS1548: Error during assembly signing. The specified key file `/var/lib/layman/dotnet/eclass/mono.snk' does not exist
```

Looks like the hardcoded path fails since I don't use layman.  So I did a workaround:

```
# mkdir -p /var/lib/layman/dotnet/eclass/
# ln -s /var/lib/portage/overlays/dotnet/eclass/mono.snk /var/lib/layman/dotnet/eclass/mono.snk
```

**Comment by ArsenShnurkov** [comment]
yes, it is hardcoded path. I can move certificate from overlay into some another package, and add dependency from that package in eclass. But first I need to understand where to install this certificate (there is mono's machine trust store, but I don't know yet how it works)

**Comment by mpkh** [comment]
maybe something alike `/etc/ssl/certs`

**Comment by ArsenShnurkov** [comment]
Mono already defines the path.

https://forums.xamarin.com/discussion/39160/system-componentmodel-licenseprovider

"or system storage (shared across users on the same computer) then it needs a shared location to exchange the data (keys in this case, but the same applies to X.509 certificates). Since there's no such place available (at least in a cross platform way) then Mono decided to define it's own."

<a href="https://github.com/mono/mono/blob/0bcbe39b148bb498742fc68416f8293ccd350fb6/mcs/tools/mono-configuration-crypto/lib/Mono.Configuration.Crypto/KeyContainerCollection.cs#L34-L38">Mono.Configuration.Crypto.KeyContainerCollection</a>

There are 2 problems:
1) may be i don't need this directory, or may be i do need another one. I don't know yet.
2) how to store keypairs in that directory (just need to read sources)

**Comment by ArsenShnurkov** [comment]
it is necessary to run sn in chroot to work with ${D}
because of sandbox
https://github.com/mono/mono/blob/0bcbe39b148bb498742fc68416f8293ccd350fb6/mcs/class/corlib/System/Environment.cs#L745-L747

**Comment by ArsenShnurkov** [comment]
how to determine names of container files after sn
http://unix.stackexchange.com/a/249238

**Comment by ArsenShnurkov** [comment]
certmgr -list -c -m trustedpublisher

Mono Certificate Manager - version 4.6.0.0
Manage X.509 certificates and CRL from stores.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Invalid Store: trustedpublisher
Valid stores are: My, AddressBook, CA, Trust and Disallowed

Any ideas which store to use? "Trust" store is not very good location, because it is used for HTTPS
How to create additional store?

**Comment by ArsenShnurkov** [comment]
sn -i create files like

/root/.config/.mono/keypairs/[1][a1b84d65-5f4a-3b63-9ba8-5ec92dc51f7c][-1].xml
/root/.config/.mono/keypairs/[1][fcf97944-61b4-65ee-8c09-c6b6e47d0492][-1].xml

(so they should be left here because ebuilds are alvays installed from root?)

and sn -m y says

     # sn -m y -i ./mcs/class/mono.snk mono
     Mono StrongName - version 4.9.0.0
     StrongName utility for signing assemblies
     Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

     Unimplemented option

**Comment by ArsenShnurkov** [comment]
for exbuild_strong there is another msbuild property called **AssemblyKeyContainerName**
http://teapotcoder.com/post/strong-naming-net-and-key-containers/
