### ISSUE TITLE
dev-dotnet/cecil no longer available

### ISSUE THREAD

**Issue by Barracuda72** [gentoo/dotnet#271]
It seems that Cecil versions from this overlay no longer available (at least from russian Yandex mirror). Then download falls back to Github repo, but it always downloads the same file no matter which commit it requests for download (I think it's the archive with latest commit). I suppose there is something wrong with Cecil or it's repository.

**Comment by ArsenShnurkov** [comment]
> I think it's the archive with latest commit

that assumption is not correct enough. There is no -9999 ebuild for cecil. Other ebuilds use specific commits.

**Comment by Barracuda72** [comment]
> There is no -9999 ebuild for cecil. Other ebuilds use specific commits.

Yes, I know that. But try to install Cecil and you will see that all ebuilds despite requesting different commits from server actually download the same ZIP file with some another commit. That's obviously wrong and that's the reason I've reported this issue.

**Comment by ArsenShnurkov** [comment]
why do you think that zip files are the same? 

    du -b `ls -1 cecil-*`
    3405462	cecil-0.10_beta1_p2016102302.zip
    3408636	cecil-0.10_beta1_p2016111002.zip
    888594	cecil-0.9.6_p20160209.zip

**Comment by mpkh** [comment]
solved?

**Comment by ArsenShnurkov** [comment]
may be not. I just noticed that github uses short commits id inside these archives (so it is necessary to fix ${S} also). Ebuilds need to be tested.

**Comment by Barracuda72** [comment]
> I just noticed that github uses short commits id inside these archives (so it is necessary to fix ${S} also).

Yes, you are right. Tried to install =dev-dotnet/cecil-0.10_beta1_p2016111002-r1 and got:

> The source directory '/media/Hdd/tmp/portage/dev-dotnet/cecil-0.10_beta1_p2016111002-r1/work/cecil-master' doesn't exist

But there is /media/Hdd/tmp/portage/dev-dotnet/cecil-0.10_beta1_p2016111002-r1/work/jbevain-cecil-045b0f9 directory. After fixing S to 

> S="${WORKDIR}/${REPO_OWNER}-${NAME}-${EGIT_COMMIT:0:7}"

I was able to build package, but installation fails due to conflict with Cecil provided by mono, specifically /usr/lib64/pkgconfig/cecil.pc file present in both packages (Mono has built-in version of Cecil). Mono is =dev-lang/mono-4.6.1.5 from official Gentoo repository.

**Comment by ArsenShnurkov** [comment]
> Mono has built-in version of Cecil

mono does wrong - https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies

**Comment by Barracuda72** [comment]
> mono does wrong

Wrong indeed, I perfectly understand that. But we have to live with it somehow...

**Comment by ArsenShnurkov** [comment]
I will try to install .pc files in pkg_postinst / pkg_prerm (in the same way as <a href="https://github.com/gentoo/dotnet/blob/a0ce339bbffbff02f393d80c6bd58746c012f2c7/dev-dotnet/mono-options/mono-options-4.4.0.0.ebuild#L55-L68">some gac install</a> go now). This will be consistent with the gacutil -i, and will probably avoid the check for collisions from portage.

I need to install into gac outside of src_install for installing binary packages.

**Comment by ArsenShnurkov** [comment]
<a href="https://gist.github.com/ArsenShnurkov/be3f5ee32a2c69c9628bc3440ee369c1">pseudocode about the idea</a>

link for me to read http://www.etalabs.net/sh_tricks.html , section "Working With Arrays"

**Comment by thesamesam** [comment]
@ArsenShnurkov I've got to the same position. I had to modify cecil to fix the fetching, find the tarball, and StrongName. Portage is complaining about Mono's bundled version.

**Comment by genterminl** [comment]
I've spent a bunch of time playing with these collision issues.  I ended up creating a USE flag "monohascecil" which is set by default, and just drops Mono.Cecil from the list of gac assemblies to be built.  That avoids the initial collision.  However, it still collides on the .pc file.  The problem there is that the file we are then trying to install refers to all the other pieces than what the one from mono does.  I thought about letting it install the pc file with the full PV name and just not symlinking it to cecil.pc, but I don't know how bad that would end up for anyone trying to use it.  Also, it would probably take modifying the gac.eclass to not +symlink in IUSE.

Additional thought (along the comments from Dec 1 above) since this overlay has the mono ebuild, would it be possible to just remove that one assembly from the gac either in the mono ebuild pkg_postinst script, or in the cecil pre-inst script?  (That assumes there is no easy way to just modify the mono build to not install it in the first place.)

If this issue can't be reopened, should someone open a new one, specifically about the collision issues?

**Comment by ArsenShnurkov** [comment]
there is no need to create new buf about collisions. What need to be done is to create gentoo-controlled process of building mono sources.

https://github.com/gentoo/dotnet/issues/142

**Comment by genterminl** [comment]
A late reply, but yes, it would be more important to be able to build mono without cecil instead of removing the conflicting files from the cecil install - those are likely to be more recent.  So - it's probably adding a depend to cecil that mono be built without cecil.  However, I can't yet find any way to drop cecil from the mono build.  Any suggestions would be most welcome.

**Comment by ArsenShnurkov** [comment]
> Any suggestions would be most welcome.

I think that complete rewriting of mono build process is necessary. I.e. this should be done with portage and msbuild instead of current gmake approach

**Comment by genterminl** [comment]
That's pushing the limits of how well I understand mono.  I only got into this because I have one package which needs mono to run :-)    I've got the shape of a mono ebuild with use flags to control parts of mono, but I'm stuck on purging cecil - I can drop the source (under external dir) but it gets called from within the labyrinth of nested Make files.  I also have quesitons on ebuild naming - I think many of these should be using _pre instead of just the fourth number.  It's a bit tougher to get the renaming right between ebuild and tarball, but I've got some working examples.

**Comment by genterminl** [comment]
Also - is there a path that gives us working versions of more recent stuff, and then refactor it and make it cleaner as a second phase?

**Comment by ArsenShnurkov** [comment]
> I think many of these should be using _pre instead of just the fourth number.
it is also possible to name them A.B.C.D_pN, where A.B.C.D is last know version and N is number of commits after that.

**Comment by genterminl** [comment]
_p is for patch.  I think these are all pre-release so I would do A.B.C_preD or A.B.C.D_preN but N seems to be the release number which is the fourth in most of the cases I've worked with.
