### ISSUE TITLE
dev-dotnet/nuget-2.8.7-r3 compile failed

### ISSUE THREAD

**Issue by soredake** [gentoo/dotnet#357]
@mpkh
```
/var/tmp/portage/dev-dotnet/nuget-2.8.7-r3/work/nuget-Release-2.8.7-MonoDevelop/Build/Build.proj (GoMono) ->
(RestorePackages target) ->
/var/tmp/portage/dev-dotnet/nuget-2.8.7-r3/work/nuget-Release-2.8.7-MonoDevelop/src/CommandLine/CommandLine.csproj (Build) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveProjectReferences target) ->
/var/tmp/portage/dev-dotnet/nuget-2.8.7-r3/work/nuget-Release-2.8.7-MonoDevelop/src/Core/Core.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	FileModifiers/XdtTransformer.cs(5,17): error CS0234: The type or namespace name 'Web' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

```
[build.log](https://github.com/gentoo/dotnet/files/1587526/buildlog.zip)

**Comment by mpkh** [comment]
@soredake is it fixed?

**Comment by soredake** [comment]
No, it is not, tried multiple mono/nuget versions.

**Comment by mpkh** [comment]
@ArsenShnurkov any ideas?

**Comment by ArsenShnurkov** [comment]
<a href="https://github.com/gentoo/dotnet/issues/244#issuecomment-351772833">my position</a> is that nuget is not necessary on gentoo.

**Comment by grbd** [comment]
I've recently managed to build it myself okay (I'm using the latest mono which I recently put in a pull request for)

but there's some weirdness involving black text, even after ```nuget update -self``` to get to the latest version. That might be related to the ncurses 6.1 patch I had to add in to get things working for mono 5.10

I'm afraid nuget is required even on gentoo, as it's a bit more than just package management.
Generally you have two options when compiling an application

  * Use a .Net library from the GAC (which is typically installed via ebuild / native package management)
  * Use a .Net library of a specific version not in the GAC (one example would be QtSharp referencing a specific version of CppSharp) which is bundled with the exe as a standalone option

There's also the case of libraries like liblog which are not actually a library but a block of code auto formatted / pasted into the source aka macro style which can be used via nuget

So for the GAC I kind of agree nuget is not necessary, but for non GAC / using different versions of a lib it's kind of a mandatory requirement.
On top of that trying to replicate all the work within the Nuget repository within the portage ebuild repo would be an immense amount of work

**Comment by ArsenShnurkov** [comment]
> an immense amount of work

This work give grantees. The guarantee that sources are present in the mirrors and that the system can be build from it. With Nuget you 1) don't have this guarantees; 2) need an internet to download them.

And there is a third way to install assemblies into directory and symlink to other applications.

**Comment by grbd** [comment]
> This work give grantees. The guarantee that sources are present in the mirrors and that the system can be build from it. With Nuget you 1) don't have this guarantees;

From an open source perspective that's fine, it's also fine for production setups.
Different strokes for different folks.
For development purposes though it's less than ideal, most .net projects are setup to use nuget, just because of easy of use (and because a lot of folks aren't that bothered about the guarantees).
Personally for example I know it's super easy to decompile .Net code because of the way IL works.
dotnet core has the one advantage in that it promotes the use of a single directory for library downloads via nuget.


> 2) need an internet to download them.

I think your going to need that anyway if your trying to compile from sources with gentoo.
Although if the packages are already installed via nuget restore then they won't need to be downloaded a 2nd time.

> And there is a third way to install assemblies into directory and symlink to other applications.

From a development perspective the build scripts are setup in such a way just to call nuget and let it sort out the rest. It's actually integrated into core at this point.

BTW I've noticed with the latest .net core sdk, it's open source but getting it to build is a massive pain (largely due to MS lagging on the build scripts). It's why the later version ebuilds in for it are binary based, I made the best efforts to build from sources but then gave up added binary ebuilds, then added a bunch of notes / docs for anyone that wanted to retry it in the future.

**Comment by Sheridan** [comment]
any news?

**Comment by murphytalk** [comment]
@soredake I was wondering is there a fix or workaround ? Thanks.

**Comment by Gooberpatrol66** [comment]
So how to I circumvent running nuget restore if I cannot install nuget?

**Comment by grbd** [comment]
If its for a dotnet core project (not the old style traditional mono / .NEt 4.x type project)
then one option is to use the nuget that's inbuilt to the dotnet exe with
"dotnet restore" / "dotnet nuget"

For non dotnet core projects (mono type stuff) nuget should still be a thing since it's no different than pip for python

**Comment by Gooberpatrol66** [comment]
Right, but I can't install nuget due to this issue.

**Comment by ArsenShnurkov** [comment]
You should trust Microsoft, why you don't want to?

**Comment by Gooberpatrol66** [comment]
I have dotnetcore-sdk-bin installed. Does that provide nuget? I'm guessing "no", because nupkg.eclass fails to find the nuget command.

**Comment by ArsenShnurkov** [comment]
Why do you want to use nupkg.eclass ? It was not updated for many years, and nobody use it. There are no ebuilds which use it (except may be "[fake](https://github.com/gentoo/dotnet/blob/17bedb24b457189974cfada68814c0313c66e5bd/dev-dotnet/fake/fake-3.23.0.ebuild#L9)").

**Comment by Gooberpatrol66** [comment]
You can't just run nuget inside an ebuild sandbox because it requires internet access, right? I thought that's what nupkg.eclass was for.

How would I "do packaging myself"?

**Comment by ArsenShnurkov** [comment]
Which ebuild does use nupkg.eclass in your case?

**Comment by Gooberpatrol66** [comment]
I'm trying to package Duplicati.

**Comment by ArsenShnurkov** [comment]
First of all, you need to create an ebuild request at bugs.gentoo.org, to have the place to discuss that. Then you should made the choice - do you need to install from sources, or binary build will be sufficient. In the first case you don't need nuget, because in gentoo portage package manager is used instead. In the second case you need just to convert Debian's package (there are guides on that).

**Comment by grbd** [comment]
Typically nuget binaries are mostly not machine specific (some are but generally they're not), they tend to be IL compiled into a binary blob, so they tend to target frameworks instead of specific machine architectures. (for example a .dll library will happily run under linux or windows without rebuilding). So in most cases a Nuget binary isn't really a binary in the traditional sense 

This is why building from source doesn't tend to be a thing with them really, unless you're making changes to the library or want to target a different framework that wasn't built for in the nuget package.

With duplicati it looks like it's targeting .Net 4.7.1 so I think you'd need to run that via mono (it's not setup for dotnet core). The easy / lazy way of doing it would be to download a copy of nuget.exe during the ebuild download stage then use that to bundle all the depends into the installed directory for duplicati

A better way might be to create an individual ebuild for each nuget package that again uses nuget to install the dll's into the global cache (again you'd need to download nuget.exe as part of the ebuild process since there is a reluctance to have it installed for some reason), although looking at some of the packages.config files there's quite a lot of nuget packages to go through
 https://github.com/duplicati/duplicati/blob/master/Duplicati/Library/Backend/AzureBlob/packages.config

**Comment by ArsenShnurkov** [comment]
> "that again uses nuget to install the dll's"

should these ebuilds have special postfix in name? like
my-package**_-bin_**-10.0.0.ebuild
my-package**_-nuget_**-10.0.0.ebuild
