### ISSUE TITLE
USE flag request: support older SDKs in newer dotnetcore-sdk-bin packages

### ISSUE THREAD

**Issue by fluffynuts** [gentoo/dotnet#508]
To continue to support a dotnet app targeting netcoreapp3.1 with dotnetcore-sdk-bin version 6 seems to be something that requires manual intervention - one can use the bash script from https://dotnet.microsoft.com/en-us/download/dotnet/scripts if one feels brave enough, with `-i /opt/dotnet_core --runtime dotnet -c 3.1`, but doing that with the install path somewhere else shows that it installs more than just the required files at `/opt/dotnet_core/shared/Microsoft.NETCore.App/3.1.22` and `/opt/dotnet_core/host/fxr/3.1.22` - it also installs the `dotnet` command and license files.

Of course, I can grab the bits I need manually, but it would be really great if there were USE flags to enable runtimes that can be supported (eg 3.1, which is in LTS). On windows, a user simply downloads the relevant sdk installer and it figures out the bits it needs to put into `C:\Program Files\dotnet` (the shared & host folders from above)

**Comment by ngg** [comment]
You can install both the `3.1` and `6.0` slots of the package and it worked for me in similar use cases.

I won't maintain the `dev-dotnet/dotnetcore-sdk-bin` package anymore, because upstream Gentoo has a "more official" .NET SDK available: https://packages.gentoo.org/packages/dev-dotnet/dotnet-sdk-bin

That package has a different method for working with multiple .NET versions, the `dotnet` binary only recognizes a single SDK which has the `dotnet-symlink` USE flag, but other slots can be used with different binaries (`dotnet-bin-3.1` for example)
Please open a bug report in Gentoo's Bugzilla for that package if there is a use-case for which this is not OK.

**Comment by fluffynuts** [comment]
thanks (:
